create extension if not exists pgcrypto;

create table if not exists public.cosplay_site_visitors (
  id bigint generated by default as identity primary key,
  ip_hash text not null unique,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visit_count bigint not null default 1
);

alter table public.cosplay_site_visitors enable row level security;

revoke all on table public.cosplay_site_visitors from anon, authenticated;

grant select on table public.cosplay_site_visitors to authenticated;

create policy "authenticated_can_read_site_visitors"
on public.cosplay_site_visitors
for select
to authenticated
using (true);

create or replace function public.register_cosplay_site_visitor(p_ip_hash text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.cosplay_site_visitors (ip_hash)
  values (p_ip_hash)
  on conflict (ip_hash) do update
    set last_seen_at = now(),
        visit_count = public.cosplay_site_visitors.visit_count + 1;
end;
$$;

revoke all on function public.register_cosplay_site_visitor(text) from public;
grant execute on function public.register_cosplay_site_visitor(text) to service_role;

create or replace function public.cosplay_unique_visitor_count()
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint from public.cosplay_site_visitors;
$$;

revoke all on function public.cosplay_unique_visitor_count() from public;
grant execute on function public.cosplay_unique_visitor_count() to authenticated;
